# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = "ember_auth_rails"
  s.version = "0.0.1"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Mike Harris"]
  s.date = "2013-08-30"
  s.description = "ember_auth_rails"
  s.email = "mharris717@gmail.com"
  s.extra_rdoc_files = [
    "README.rdoc"
  ]
  s.files = [
    "Gemfile",
    "Gemfile.lock",
    "Guardfile",
    "MIT-LICENSE",
    "README.rdoc",
    "Rakefile",
    "VERSION",
    "app/assets/images/ember_auth_rails/.gitkeep",
    "app/assets/javascripts/ember_auth_rails/.gitkeep",
    "app/assets/stylesheets/ember_auth_rails/.gitkeep",
    "app/controllers/.gitkeep",
    "app/controllers/ember_users_controller.rb",
    "app/controllers/sessions_controller.rb",
    "app/helpers/.gitkeep",
    "app/helpers/ember_auth_helper.rb",
    "app/mailers/.gitkeep",
    "app/models/.gitkeep",
    "app/models/ember_auth_rails/user_mod.rb",
    "app/models/user.rb",
    "app/serializers/user_serializer.rb",
    "app/views/.gitkeep",
    "config/initializers/devise.rb",
    "config/routes.rb",
    "db/migrate/20130601155410_devise_create_users.rb",
    "db/migrate/20130601155411_user_auth_token.rb",
    "ember_auth_rails.gemspec",
    "lib/ember_auth_rails.rb",
    "lib/ember_auth_rails/engine.rb",
    "lib/ember_auth_rails/version.rb",
    "lib/tasks/ember_auth_rails_tasks.rake",
    "script/rails",
    "spec/controllers/ember_users_controller_spec.rb",
    "spec/controllers/sessions_controller_spec.rb",
    "spec/controllers/widgets_controller_spec.rb",
    "spec/dummy/.env",
    "spec/dummy/README.rdoc",
    "spec/dummy/Rakefile",
    "spec/dummy/app/assets/javascripts/application.js",
    "spec/dummy/app/assets/javascripts/widgets.js",
    "spec/dummy/app/assets/stylesheets/application.css",
    "spec/dummy/app/assets/stylesheets/widgets.css",
    "spec/dummy/app/controllers/application_controller.rb",
    "spec/dummy/app/controllers/widgets_controller.rb",
    "spec/dummy/app/helpers/application_helper.rb",
    "spec/dummy/app/helpers/widgets_helper.rb",
    "spec/dummy/app/mailers/.gitkeep",
    "spec/dummy/app/models/.gitkeep",
    "spec/dummy/app/models/widget.rb",
    "spec/dummy/app/serializers/widget_serializer.rb",
    "spec/dummy/app/views/layouts/application.html.erb",
    "spec/dummy/app/views/widgets/index.html.haml",
    "spec/dummy/config.ru",
    "spec/dummy/config/application.rb",
    "spec/dummy/config/boot.rb",
    "spec/dummy/config/database.yml",
    "spec/dummy/config/environment.rb",
    "spec/dummy/config/environments/development.rb",
    "spec/dummy/config/environments/production.rb",
    "spec/dummy/config/environments/test.rb",
    "spec/dummy/config/initializers/backtrace_silencers.rb",
    "spec/dummy/config/initializers/inflections.rb",
    "spec/dummy/config/initializers/mime_types.rb",
    "spec/dummy/config/initializers/secret_token.rb",
    "spec/dummy/config/initializers/session_store.rb",
    "spec/dummy/config/initializers/wrap_parameters.rb",
    "spec/dummy/config/locales/en.yml",
    "spec/dummy/config/routes.rb",
    "spec/dummy/db/migrate/20130703135528_create_users.multiauth_engine.rb",
    "spec/dummy/db/migrate/20130703135529_create_identities.multiauth_engine.rb",
    "spec/dummy/db/migrate/20130703136445_user_auth_token.ember_auth_rails_engine.rb",
    "spec/dummy/db/migrate/20130703142306_create_widgets.rb",
    "spec/dummy/db/schema.rb",
    "spec/dummy/db/seeds.rb",
    "spec/dummy/lib/assets/.gitkeep",
    "spec/dummy/log/.gitkeep",
    "spec/dummy/public/404.html",
    "spec/dummy/public/422.html",
    "spec/dummy/public/500.html",
    "spec/dummy/public/favicon.ico",
    "spec/dummy/script/rails",
    "spec/spec_helper.rb",
    "spec/support/devise.rb",
    "spec/support/make_user.rb",
    "test/ember_auth_rails_test.rb",
    "test/integration/navigation_test.rb",
    "test/test_helper.rb"
  ]
  s.homepage = "http://github.com/mharris717/ember_auth_rails"
  s.licenses = ["MIT"]
  s.require_paths = ["lib"]
  s.rubygems_version = "1.8.25"
  s.summary = "ember_auth_rails"

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<jquery-rails>, [">= 0"])
      s.add_runtime_dependency(%q<devise>, [">= 0"])
      s.add_runtime_dependency(%q<rails>, ["= 3.2.13"])
      s.add_runtime_dependency(%q<active_model_serializers>, [">= 0"])
      s.add_runtime_dependency(%q<devise>, [">= 0"])
      s.add_development_dependency(%q<rspec>, [">= 2.13.0"])
      s.add_development_dependency(%q<rdoc>, ["~> 3.12"])
      s.add_development_dependency(%q<bundler>, ["~> 1.1"])
      s.add_development_dependency(%q<jeweler>, ["~> 1.8.4"])
      s.add_development_dependency(%q<sqlite3>, [">= 0"])
      s.add_development_dependency(%q<rspec-rails>, ["~> 2.0"])
      s.add_development_dependency(%q<guard>, [">= 0"])
      s.add_development_dependency(%q<guard-rspec>, [">= 0"])
      s.add_development_dependency(%q<guard-spork>, [">= 0"])
      s.add_development_dependency(%q<rb-fsevent>, ["~> 0.9"])
      s.add_development_dependency(%q<rr>, [">= 1.1"])
      s.add_development_dependency(%q<factory_girl_rails>, [">= 0"])
      s.add_development_dependency(%q<lre>, [">= 0"])
      s.add_development_dependency(%q<rspec-mocks>, ["~> 2.13.0"])
    else
      s.add_dependency(%q<jquery-rails>, [">= 0"])
      s.add_dependency(%q<devise>, [">= 0"])
      s.add_dependency(%q<rails>, ["= 3.2.13"])
      s.add_dependency(%q<active_model_serializers>, [">= 0"])
      s.add_dependency(%q<devise>, [">= 0"])
      s.add_dependency(%q<rspec>, [">= 2.13.0"])
      s.add_dependency(%q<rdoc>, ["~> 3.12"])
      s.add_dependency(%q<bundler>, ["~> 1.1"])
      s.add_dependency(%q<jeweler>, ["~> 1.8.4"])
      s.add_dependency(%q<sqlite3>, [">= 0"])
      s.add_dependency(%q<rspec-rails>, ["~> 2.0"])
      s.add_dependency(%q<guard>, [">= 0"])
      s.add_dependency(%q<guard-rspec>, [">= 0"])
      s.add_dependency(%q<guard-spork>, [">= 0"])
      s.add_dependency(%q<rb-fsevent>, ["~> 0.9"])
      s.add_dependency(%q<rr>, [">= 1.1"])
      s.add_dependency(%q<factory_girl_rails>, [">= 0"])
      s.add_dependency(%q<lre>, [">= 0"])
      s.add_dependency(%q<rspec-mocks>, ["~> 2.13.0"])
    end
  else
    s.add_dependency(%q<jquery-rails>, [">= 0"])
    s.add_dependency(%q<devise>, [">= 0"])
    s.add_dependency(%q<rails>, ["= 3.2.13"])
    s.add_dependency(%q<active_model_serializers>, [">= 0"])
    s.add_dependency(%q<devise>, [">= 0"])
    s.add_dependency(%q<rspec>, [">= 2.13.0"])
    s.add_dependency(%q<rdoc>, ["~> 3.12"])
    s.add_dependency(%q<bundler>, ["~> 1.1"])
    s.add_dependency(%q<jeweler>, ["~> 1.8.4"])
    s.add_dependency(%q<sqlite3>, [">= 0"])
    s.add_dependency(%q<rspec-rails>, ["~> 2.0"])
    s.add_dependency(%q<guard>, [">= 0"])
    s.add_dependency(%q<guard-rspec>, [">= 0"])
    s.add_dependency(%q<guard-spork>, [">= 0"])
    s.add_dependency(%q<rb-fsevent>, ["~> 0.9"])
    s.add_dependency(%q<rr>, [">= 1.1"])
    s.add_dependency(%q<factory_girl_rails>, [">= 0"])
    s.add_dependency(%q<lre>, [">= 0"])
    s.add_dependency(%q<rspec-mocks>, ["~> 2.13.0"])
  end
end

